In [1]:
# Numpy
# Scipy
# Matplotlib
# sympy
# pandas

In [2]:
! pip install Numpy

In [3]:
import numpy

In [4]:
x = 5
y = numpy.sin(x)

y

np.float64(-0.9589242746631385)

In [5]:
x = 5
y = numpy.cos(x)

y

np.float64(0.28366218546322625)

In [7]:
import numpy as np
from numpy import *

In [8]:
x = 5
y = cos(x)

y

np.float64(0.28366218546322625)

In [9]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
b = np.array([[-3,4,6],[0,5,7]])
b

array([[-3,  4,  6],
       [ 0,  5,  7]])

In [14]:
b = np.array([[-3,4,6,3],[0,5,7,5],[0,8,9,6]])
b

array([[-3,  4,  6,  3],
       [ 0,  5,  7,  5],
       [ 0,  8,  9,  6]])

In [18]:
x = 45
x = sin(45)
x

np.float64(0.8509035245341184)

In [19]:
import numpy

In [20]:
x = 45
x = numpy.sin(x)
x

np.float64(0.8509035245341184)

In [21]:
x = 45
x = numpy.cos(x)
x

np.float64(0.5253219888177297)

In [22]:
x = 45
x = numpy.tan(x)
x

np.float64(1.6197751905438615)

In [23]:
import numpy as np
from numpy import *

In [24]:
x = 90
y = np.sin(x)
y

np.float64(0.8939966636005579)

In [25]:
x = 90
y = np.cos(x)
y

np.float64(-0.4480736161291701)

In [27]:
x = 90
y = np.tan(x)
y

np.float64(-1.995200412208242)

In [28]:
# terdapat dua variabel yaitu adan b

a = [1, 2]
b = [3, 4]

# jumlahkan variabel a & b
hasil = a + b

print(hasil)

[1, 2, 3, 4]


In [29]:
import numpy as np
matrik_a = np.array([1, 2])
matrik_b = np.array([3, 4])
hasil = matrik_a + matrik_b
print(hasil)

[4 6]
